### ISSUE TITLE
Null safety support (Flutter 2)

### ISSUE THREAD

**Issue by geekydiamond** [pollfish/flutter-plugin-pollfish#13]
Hi guys,

Could you advise how soon the plugin will move to Flutter 2 (and null safety)?

Unfortunately it's blocking migration of our app to Flutter 2.

Thanks, Tom

**Comment by fotism23** [comment]
Hello, sorry for the delayed response

We have just released version 2.0.1 which adds support for Flutter 2

**Comment by geekydiamond** [comment]
Unfortunately the plugin still does not appear to be null safe :(

**Comment by fotism23** [comment]
Hello @geekydiamond 

We have just released v3.0.0 which opts the Pollfish Flutter Plugin into Null Safety.

Please take some time to read the migration guide since v3.0.0 has a slightly different API.

Thanks
